os:
  - osx

language: java

before_install:
  - brew update
  
install:
  - brew cask install google-chrome
  - brew install chromedriver
  - brew install gauge
  - gauge --install java
  - gauge --install html-report

script:
  - gauge specs
